apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us-central1-docker.pkg.dev/my-first-gcp-instance-323404/my-images/mynginx:2024-08-21T1017
        ports:
        - containerPort: 80